"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

t1 = 1
t2 = 2
upperLimit = 4000000
evenfib = []


def main(t1, t2, upperLimit):
    t3 = 0
    while t3 < upperLimit:
        t3 = t1 + t2
        if t3 % 2 == 0:
            evenfib.append(t3)
        t2 = t3
        t1 = t2
    print(sum(evenfib))


main(t1, t2, upperLimit)